### ISSUE TITLE
Add installation instructions to pi-hole

### ISSUE THREAD

**Issue by E3V3A** [CHEF-KOCH/CK-s-Raspberry-Pi-3-config#1]
You forgot to add installation links and instructions to [pi-hole](https://github.com/pi-hole/pi-hole).

**Comment by CHEF-KOCH** [comment]
https://github.com/CHEF-KOCH/CK-s-Raspberry-Pi-3-config/commit/92299fd764a3dccc92137118252fe484bd2f7075
